name: Release Asset

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Check build status
        run: |
          if [ $? -eq 0 ]
          then
            echo "Build successful!"
          else
            echo "Build failed!"
            exit 1
          fi
          
      - name: Zip build
        run: zip -r -j ./dist.zip ./dist

      - name: Define release version
        run: |
          echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist.zip
          asset_name: ${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
