name: Create Tag and Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Print debugging
        run: |
          echo Current branch: $(git rev-parse --abbrev-ref HEAD)
          echo Current commit: $(git rev-parse HEAD)
          echo Current tag: $(git describe --tags --abbrev=0 || echo 0.0)

      - name: Get current tag version
        id: get_version
        run: |
          echo "VERSION=$(git describe --tags --abbrev=0 || echo 0.0)" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date -u +"%y%m%d.%H%M%S" --date=now)" >> $GITHUB_ENV

      - name: Create new tag
        id: create_tag
        run: |
          git tag ${{ env.VERSION }}-${{ env.RELEASE_DATE }}
          echo "TAG_REF=${{ env.VERSION }}-${{ env.RELEASE_DATE }}" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_REF }}
          release_name: ${{ env.TAG_REF }}
          draft: false # create a published release
          body: |
            Automatic release of ${{ env.TAG_REF }}

      - name: Push tag and release reference
        uses: EndBug/add-and-commit@v7
        with:
          message: "Automatic release of ${{ env.TAG_REF }}"
          add: "."
          branch: main
          signoff: true
          author_name: "GitHub Action"
          author_email: "action@github.com"
          sign_key: ${{ secrets.GPG_PRIVATE_KEY }}
