name: Create Tag and Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current tag version
        id: get_version
        run: |
          echo ::set-output name=version::$(git describe --tags --abbrev=0 || echo 0.0)
          echo ::set-output name=releaseDate::$(date -u +"%y%m%d.%H%M%S" --date=now)

      - name: Create new tag
        id: create_tag
        run: |
          git tag ${{ steps.get_version.outputs.version }} ${{ steps.get_version.outputs.releaseDate }}
          echo ::set-output name=tag_ref::${{ steps.get_version.outputs.version }} ${{ steps.get_version.outputs.releaseDate }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_ref }}
          release_name: Release ${{ steps.create_tag.outputs.tag_ref }}
          body: |
            Release ${{ steps.create_tag.outputs.tag_ref }}

      - name: Push tag and release reference
        uses: EndBug/add-and-commit@v7
        with:
          message: "Release ${{ steps.create_tag.outputs.tag_ref }}"
          add: "."
          branch: main
          signoff: true
          author_name: "GitHub Action"
          author_email: "action@github.com"
          sign_key: ${{ secrets.GPG_PRIVATE_KEY }}
